// Copyright (c) 2023 Cisco and/or its affiliates.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generator

const suiteTemplate = `// Code generated by gotestmd DO NOT EDIT.
package {{ .Name }}

import(
	{{ .Imports }}
)

type Suite struct {
	{{ .Fields }}
}

func (s *Suite) SetupSuite() {
	{{ .Setup }}
	{{ if or .Run .Cleanup }}
	r := s.Runner("{{.Dir}}")
	{{ end }}
	{{ .Cleanup }}
	{{ .Run }}

{{ if .TestIncludedSuites }}
	s.RunIncludedSuites()
}

func (s *Suite) RunIncludedSuites() {
	{{ .TestIncludedSuites }}
{{ end }}
}
`

const includedSuiteTemplate = `
	{{ range .Suites }}
		s.Run("{{ .Title }}", func() {
			suite.Run(s.T(), &s.{{ .Name }}Suite)
		})
	{{ end }}
`

const bashSuiteTemplate = `
function setup() {
	{{ .Setup }}
	cd {{ .Dir }}

	{{ .Run }}
}

function cleanup() {
	{{ .Cleanup }}
}

`
